# Generated by Django 5.0.14 on 2026-09-21 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('ramo', 'Ramo'), ('planta', 'Planta'), ('arreglo', 'Arreglo floral'), ('accesorio', 'Accesorio')], default='ramo', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
