# Generated by Django 5.0.14 on 2026-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreriapp', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
