# Generated by Django 5.0.14 on 2026-09-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreriapp', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ramo', 'Ramo'), ('canasta', 'Canasta'), ('jarron', 'Jarrón')], default='ramo', max_length=20),
        ),
    ]
